substitutions:
  name: project_name
  friendly_name: "Friendly project name"
  board: 

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp8266:
  board: ${board}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name} Fallback AP
    password: !secret project_name_ap_password

captive_portal:
  
logger:

api:
  encryption:
    key: !secret project_name_api_encryption_key

ota:
  - platform: esphome
    password: !secret project_name_ota_password

text_sensor:
  - platform: version
    name: ESPHome Version - ${friendly_name}

  - platform: wifi_info
    ip_address: 
      name: IP - ${friendly_name}

button:
  - platform: restart
    name: Restart ${friendly_name}